# _config.yaml

title: "Smart Traffic Management System"
description: "Sistem berbasis AI yang mengoptimalkan durasi lampu lalu lintas secara real-time berdasarkan kepadatan kendaraan untuk mengurangi kemacetan dan meningkatkan efisiensi transportasi di perkotaan."
baseurl: "/Smart-Traffic-Management-System"
url: "https://github.com/alexchtst-01/Smart-Traffic-Management-System"
author:
  name: "Alex Cinatra Hutasoit"
  email: "alex@example.com" # Ganti dengan email Anda
  bio: "Pengembang sistem manajemen lalu lintas pintar berbasis AI"
  avatar: "/assets/images/avatar.jpg" # Ganti dengan gambar avatar yang sesuai

# Permalink structure for your pages
permalink: /:title/

# Theme settings
theme: "minima"  # Anda bisa mengganti tema jika perlu, seperti "jekyll-theme-cayman" atau tema lainnya

# Social links (optional)
social:
  - name: "GitHub"
    url: "https://github.com/alexchtst-01"
  - name: "LinkedIn"
    url: "https://linkedin.com/in/alexcinatra"

# Navigation settings (optional)
navbar:
  - title: "Home"
    url: "/"
  - title: "Fitur Utama"
    url: "#fitur"
  - title: "Instalasi"
    url: "#installation"
  - title: "Tentang Kami"
    url: "#about"
  - title: "Kontak"
    url: "#contact"

# Footer settings (optional)
footer:
  text: "© 2025 Tetua Pancasila - Smart Traffic Management System"
  links:
    - title: "Dokumentasi"
      url: "/docs"
    - title: "GitHub Repo"
      url: "https://github.com/alexchtst-01/Smart-Traffic-Management-System"

# Include default posts and pages (optional)
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Markdown settings (optional)
markdown: kramdown
